# Generated by Django 5.0.7 on 2024-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="test",
            field=models.TextField(blank=True),
        ),
    ]
