# Generated by Django 5.0.7 on 2024-07-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="test",
        ),
    ]
